// Code generated by protoc-gen-govalidators. DO NOT EDIT.

package validatortest

import (
	errors "errors"
	fmt "fmt"
	go_proto_validators "github.com/mwitkow/go-proto-validators"
	regexp "regexp"
)

var ValidatorMessage_EmbeddedMessageIdentifierRE = regexp.MustCompile(`^[a-z]{2,5}$`)

func (m *ValidatorMessage_EmbeddedMessage) Validate() error {
	if m.Identifier != nil {
		if !ValidatorMessage_EmbeddedMessageIdentifierRE.MatchString(string(m.GetIdentifier())) {
			return go_proto_validators.FieldError("Identifier", errors.New(`Identifier should match regular expression "^[a-z]{2,5}$"`))
		}
	}

	if m.GetSomeValue() <= 0 {
		return go_proto_validators.FieldError("SomeValue", errors.New("SomeValue is not greater than 0"))
	}
	if m.GetSomeValue() >= 100 {
		return go_proto_validators.FieldError("SomeValue", errors.New("SomeValue is not smaller than 100"))
	}

	return nil
}

var ValidatorMessageStringReqRE = regexp.MustCompile(`^.{2,5}$`)
var ValidatorMessageStringOptRE = regexp.MustCompile(`^.{2,5}$`)
var ValidatorMessageStringNoQuotesRE = regexp.MustCompile(`^[^"]{2,5}$`)
var ValidatorMessageStringUnescapedRE = regexp.MustCompile(`[\p{L}\p{N}]({\p{L}\p{N}_- ]{0,28}[\p{L}\p{N}])?.`)
var ValidatorMessageUUIDAnyRE = regexp.MustCompile(`^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[1-5][a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}$`)
var ValidatorMessageUUID4NotEmptyRE = regexp.MustCompile(`^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[4][a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}$`)

func (m *ValidatorMessage) Validate() error {
	if !ValidatorMessageStringReqRE.MatchString(string(m.GetStringReq())) {
		return go_proto_validators.FieldError("StringReq", errors.New(`StringReq should match regular expression "^.{2,5}$"`))
	}

	if m.StringOpt != nil {
		if !ValidatorMessageStringOptRE.MatchString(string(m.GetStringOpt())) {
			return go_proto_validators.FieldError("StringOpt", errors.New(`StringOpt should match regular expression "^.{2,5}$"`))
		}
	}

	if !ValidatorMessageStringNoQuotesRE.MatchString(string(m.GetStringNoQuotes())) {
		return go_proto_validators.FieldError("StringNoQuotes", errors.New(`StringNoQuotes should match regular expression "^[^\"]{2,5}$"`))
	}

	if !ValidatorMessageStringUnescapedRE.MatchString(string(m.GetStringUnescaped())) {
		return go_proto_validators.FieldError("StringUnescaped", errors.New(`StringUnescaped should match regular expression "[\\p{L}\\p{N}]({\\p{L}\\p{N}_- ]{0,28}[\\p{L}\\p{N}])?."`))
	}

	if m.GetIntReq() <= 10 {
		return go_proto_validators.FieldError("IntReq", errors.New("IntReq is not greater than 10"))
	}

	for _, item := range m.GetIntRep() {
		if item <= 10 {
			return go_proto_validators.FieldError("IntRep", errors.New("IntRep is not greater than 10"))
		}
	}

	if m.GetEmbeddedReq() != nil {
		if err := go_proto_validators.CallValidatorIfExists(m.GetEmbeddedReq()); err != nil {
			return go_proto_validators.FieldError("EmbeddedReq", err)
		}
	}

	for _, item := range m.GetEmbeddedRep() {
		if item != nil {
			if err := go_proto_validators.CallValidatorIfExists(item); err != nil {
				return go_proto_validators.FieldError("EmbeddedRep", err)
			}
		}
	}

	if m.CustomErrorInt != nil {
		if m.GetCustomErrorInt() <= 10 {
			return go_proto_validators.FieldError("CustomErrorInt", errors.New("My Custom Error"))
		}
	}

	if m.GetStrictSomeDoubleReq() <= 0.3 {
		return go_proto_validators.FieldError("StrictSomeDoubleReq", errors.New("StrictSomeDoubleReq is not greater than 0.3"))
	}
	if m.GetStrictSomeDoubleReq() >= 0.7000000000000001 {
		return go_proto_validators.FieldError("StrictSomeDoubleReq", errors.New("StrictSomeDoubleReq is not smaller than 0.7000000000000001"))
	}

	for _, item := range m.GetStrictSomeDoubleRep() {
		if item <= 0.3 {
			return go_proto_validators.FieldError("StrictSomeDoubleRep", errors.New("StrictSomeDoubleRep is not greater than 0.3"))
		}
		if item >= 0.7000000000000001 {
			return go_proto_validators.FieldError("StrictSomeDoubleRep", errors.New("StrictSomeDoubleRep is not smaller than 0.7000000000000001"))
		}
	}

	if m.GetStrictSomeFloatReq() <= 0.3 {
		return go_proto_validators.FieldError("StrictSomeFloatReq", errors.New("StrictSomeFloatReq is not greater than 0.3"))
	}
	if m.GetStrictSomeFloatReq() >= 0.7000000000000001 {
		return go_proto_validators.FieldError("StrictSomeFloatReq", errors.New("StrictSomeFloatReq is not smaller than 0.7000000000000001"))
	}

	for _, item := range m.GetStrictSomeFloatRep() {
		if item <= 0.3 {
			return go_proto_validators.FieldError("StrictSomeFloatRep", errors.New("StrictSomeFloatRep is not greater than 0.3"))
		}
		if item >= 0.7000000000000001 {
			return go_proto_validators.FieldError("StrictSomeFloatRep", errors.New("StrictSomeFloatRep is not smaller than 0.7000000000000001"))
		}
	}

	if m.GetSomeDoubleReq() < 0.25 {
		return go_proto_validators.FieldError("SomeDoubleReq", errors.New("SomeDoubleReq is not greater than or equal to 0.25"))
	}
	if m.GetSomeDoubleReq() > 0.75 {
		return go_proto_validators.FieldError("SomeDoubleReq", errors.New("SomeDoubleReq is not smaller than or equal to 0.75"))
	}

	for _, item := range m.GetSomeDoubleRep() {
		if item < 0.25 {
			return go_proto_validators.FieldError("SomeDoubleRep", errors.New("SomeDoubleRep is not greater than or equal to 0.25"))
		}
		if item > 0.75 {
			return go_proto_validators.FieldError("SomeDoubleRep", errors.New("SomeDoubleRep is not smaller than or equal to 0.75"))
		}
	}

	if m.GetSomeFloatReq() < 0.25 {
		return go_proto_validators.FieldError("SomeFloatReq", errors.New("SomeFloatReq is not greater than or equal to 0.25"))
	}
	if m.GetSomeFloatReq() > 0.75 {
		return go_proto_validators.FieldError("SomeFloatReq", errors.New("SomeFloatReq is not smaller than or equal to 0.75"))
	}

	for _, item := range m.GetSomeFloatRep() {
		if item < 0.25 {
			return go_proto_validators.FieldError("SomeFloatRep", errors.New("SomeFloatRep is not greater than or equal to 0.25"))
		}
		if item > 0.75 {
			return go_proto_validators.FieldError("SomeFloatRep", errors.New("SomeFloatRep is not smaller than or equal to 0.75"))
		}
	}

	if string(m.GetSomeNonEmptyString()) == "" {
		return go_proto_validators.FieldError("SomeNonEmptyString", errors.New("SomeNonEmptyString should not be empty"))
	}

	if len(m.GetRepeated()) > 5 {
		return go_proto_validators.FieldError("Repeated", fmt.Errorf("Repeated has %d elements whereas a maximum of 5 is allowed", len(m.GetRepeated())))
	}

	if len(m.GetRepeated()) < 2 {
		return go_proto_validators.FieldError("Repeated", fmt.Errorf("Repeated has %d elements whereas a minimum of 2 is required", len(m.GetRepeated())))
	}

	if m.SomeStringLtReq != nil {
		if len(m.GetSomeStringLtReq()) <= 2 {
			return go_proto_validators.FieldError("SomeStringLtReq", errors.New("SomeStringLtReq should have a length greater than 2"))
		}
	}

	if m.SomeStringGtReq != nil {
		if len(m.GetSomeStringGtReq()) >= 12 {
			return go_proto_validators.FieldError("SomeStringGtReq", errors.New("SomeStringGtReq should have a length smaller than 12"))
		}
	}

	if m.SomeStringEqReq != nil {
		if len(m.GetSomeStringEqReq()) != 10 {
			return go_proto_validators.FieldError("SomeStringEqReq", errors.New("SomeStringEqReq should be of length 10"))
		}
	}

	if m.SomeBytesLtReq != nil {
		if len(m.GetSomeBytesLtReq()) <= 5 {
			return go_proto_validators.FieldError("SomeBytesLtReq", errors.New("SomeBytesLtReq should have a length greater than 5"))
		}
	}

	if m.SomeBytesGtReq != nil {
		if len(m.GetSomeBytesGtReq()) >= 20 {
			return go_proto_validators.FieldError("SomeBytesGtReq", errors.New("SomeBytesGtReq should have a length smaller than 20"))
		}
	}

	if m.SomeBytesEqReq != nil {
		if len(m.GetSomeBytesEqReq()) != 12 {
			return go_proto_validators.FieldError("SomeBytesEqReq", errors.New("SomeBytesEqReq should be of length 12"))
		}
	}

	if m.UUIDAny != nil {
		if !ValidatorMessageUUIDAnyRE.MatchString(string(m.GetUUIDAny())) {
			return go_proto_validators.FieldError("UUIDAny", errors.New("UUIDAny should match regular expression '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[0][a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}$'"))
		}
	}

	if !ValidatorMessageUUID4NotEmptyRE.MatchString(string(m.GetUUID4NotEmpty())) {
		return go_proto_validators.FieldError("UUID4NotEmpty", errors.New("UUID4NotEmpty should match regular expression '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[4][a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}$'"))
	}

	if _, ok := EnumProto2_name[int32(m.GetSomeEnum())]; !ok {
		return go_proto_validators.FieldError("SomeEnum", errors.New("someEnum should correspond to a valid enum value"))
	}

	if _, ok := ValidatorMessage_EmbeddedEnum_name[int32(m.GetSomeEmbeddedEnum())]; !ok {
		return go_proto_validators.FieldError("SomeEmbeddedEnum", errors.New("someEmbeddedEnum should correspond to a valid enum value"))
	}

	return nil
}
