// Code generated by protoc-gen-govalidators. DO NOT EDIT.

package validatortest

import (
	errors "errors"
	fmt "fmt"
	go_proto_validators "github.com/mwitkow/go-proto-validators"
	regexp "regexp"
)

var ValidatorMessage3_EmbeddedMessageIdentifierRE = regexp.MustCompile(`^[a-z]{2,5}$`)

func (m *ValidatorMessage3_EmbeddedMessage) Validate() error {
	if !ValidatorMessage3_EmbeddedMessageIdentifierRE.MatchString(string(m.GetIdentifier())) {
		return go_proto_validators.FieldError("Identifier", errors.New(`Identifier should match regular expression "^[a-z]{2,5}$"`))
	}

	if m.GetSomeValue() <= 0 {
		return go_proto_validators.FieldError("SomeValue", errors.New("SomeValue is not greater than 0"))
	}
	if m.GetSomeValue() >= 100 {
		return go_proto_validators.FieldError("SomeValue", errors.New("SomeValue is not smaller than 100"))
	}

	return nil
}

var ValidatorMessage3SomeStringRE = regexp.MustCompile(`^.{2,5}$`)
var ValidatorMessage3SomeStringRepRE = regexp.MustCompile(`^.{2,5}$`)
var ValidatorMessage3SomeStringNoQuotesRE = regexp.MustCompile(`^[^"]{2,5}$`)
var ValidatorMessage3SomeStringUnescapedRE = regexp.MustCompile(`[\p{L}\p{N}]({\p{L}\p{N}_- ]{0,28}[\p{L}\p{N}])?.`)
var ValidatorMessage3UUIDAnyRE = regexp.MustCompile(`^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[1-5][a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}$`)
var ValidatorMessage3UUID4NotEmptyRE = regexp.MustCompile(`^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[4][a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}$`)

func (m *ValidatorMessage3) Validate() error {
	if !ValidatorMessage3SomeStringRE.MatchString(string(m.GetSomeString())) {
		return go_proto_validators.FieldError("SomeString", errors.New(`SomeString should match regular expression "^.{2,5}$"`))
	}

	for _, item := range m.GetSomeStringRep() {
		if !ValidatorMessage3SomeStringRepRE.MatchString(string(item)) {
			return go_proto_validators.FieldError("SomeStringRep", errors.New(`SomeStringRep should match regular expression "^.{2,5}$"`))
		}
	}

	if !ValidatorMessage3SomeStringNoQuotesRE.MatchString(string(m.GetSomeStringNoQuotes())) {
		return go_proto_validators.FieldError("SomeStringNoQuotes", errors.New(`SomeStringNoQuotes should match regular expression "^[^\"]{2,5}$"`))
	}

	if !ValidatorMessage3SomeStringUnescapedRE.MatchString(string(m.GetSomeStringUnescaped())) {
		return go_proto_validators.FieldError("SomeStringUnescaped", errors.New(`SomeStringUnescaped should match regular expression "[\\p{L}\\p{N}]({\\p{L}\\p{N}_- ]{0,28}[\\p{L}\\p{N}])?."`))
	}

	if m.GetSomeInt() <= 10 {
		return go_proto_validators.FieldError("SomeInt", errors.New("SomeInt is not greater than 10"))
	}

	for _, item := range m.GetSomeIntRep() {
		if item <= 10 {
			return go_proto_validators.FieldError("SomeIntRep", errors.New("SomeIntRep is not greater than 10"))
		}
	}

	if m.GetSomeEmbedded() != nil {
		if err := go_proto_validators.CallValidatorIfExists(m.GetSomeEmbedded()); err != nil {
			return go_proto_validators.FieldError("SomeEmbedded", err)
		}
	}

	if m.GetSomeEmbeddedExists() != nil {
		if err := go_proto_validators.CallValidatorIfExists(m.GetSomeEmbeddedExists()); err != nil {
			return go_proto_validators.FieldError("SomeEmbeddedExists", err)
		}
	}
	if m.GetSomeEmbeddedExists() == nil {
		return go_proto_validators.FieldError("SomeEmbeddedExists", errors.New("SomeEmbeddedExists should be set"))
	}

	for _, item := range m.GetSomeEmbeddedRep() {
		if item != nil {
			if err := go_proto_validators.CallValidatorIfExists(item); err != nil {
				return go_proto_validators.FieldError("SomeEmbeddedRep", err)
			}
		}
	}

	if m.GetCustomErrorInt() >= 10 {
		return go_proto_validators.FieldError("CustomErrorInt", errors.New("My Custom Error"))
	}

	if m.GetStrictSomeDouble() <= 0.3 {
		return go_proto_validators.FieldError("StrictSomeDouble", errors.New("StrictSomeDouble is not greater than 0.3"))
	}
	if m.GetStrictSomeDouble() >= 0.7000000000000001 {
		return go_proto_validators.FieldError("StrictSomeDouble", errors.New("StrictSomeDouble is not smaller than 0.7000000000000001"))
	}

	for _, item := range m.GetStrictSomeDoubleRep() {
		if item <= 0.3 {
			return go_proto_validators.FieldError("StrictSomeDoubleRep", errors.New("StrictSomeDoubleRep is not greater than 0.3"))
		}
		if item >= 0.7000000000000001 {
			return go_proto_validators.FieldError("StrictSomeDoubleRep", errors.New("StrictSomeDoubleRep is not smaller than 0.7000000000000001"))
		}
	}

	for _, item := range m.GetStrictSomeDoubleRepNonNull() {
		if item <= 0.3 {
			return go_proto_validators.FieldError("StrictSomeDoubleRepNonNull", errors.New("StrictSomeDoubleRepNonNull is not greater than 0.3"))
		}
		if item >= 0.7000000000000001 {
			return go_proto_validators.FieldError("StrictSomeDoubleRepNonNull", errors.New("StrictSomeDoubleRepNonNull is not smaller than 0.7000000000000001"))
		}
	}

	if m.GetStrictSomeFloat() <= 0.3 {
		return go_proto_validators.FieldError("StrictSomeFloat", errors.New("StrictSomeFloat is not greater than 0.3"))
	}
	if m.GetStrictSomeFloat() >= 0.7000000000000001 {
		return go_proto_validators.FieldError("StrictSomeFloat", errors.New("StrictSomeFloat is not smaller than 0.7000000000000001"))
	}

	for _, item := range m.GetStrictSomeFloatRep() {
		if item <= 0.3 {
			return go_proto_validators.FieldError("StrictSomeFloatRep", errors.New("StrictSomeFloatRep is not greater than 0.3"))
		}
		if item >= 0.7000000000000001 {
			return go_proto_validators.FieldError("StrictSomeFloatRep", errors.New("StrictSomeFloatRep is not smaller than 0.7000000000000001"))
		}
	}

	for _, item := range m.GetStrictSomeFloatRepNonNull() {
		if item <= 0.3 {
			return go_proto_validators.FieldError("StrictSomeFloatRepNonNull", errors.New("StrictSomeFloatRepNonNull is not greater than 0.3"))
		}
		if item >= 0.7000000000000001 {
			return go_proto_validators.FieldError("StrictSomeFloatRepNonNull", errors.New("StrictSomeFloatRepNonNull is not smaller than 0.7000000000000001"))
		}
	}

	if m.GetSomeDouble() < 0.25 {
		return go_proto_validators.FieldError("SomeDouble", errors.New("SomeDouble is not greater than or equal to 0.25"))
	}
	if m.GetSomeDouble() > 0.75 {
		return go_proto_validators.FieldError("SomeDouble", errors.New("SomeDouble is not smaller than or equal to 0.75"))
	}

	for _, item := range m.GetSomeDoubleRep() {
		if item < 0.25 {
			return go_proto_validators.FieldError("SomeDoubleRep", errors.New("SomeDoubleRep is not greater than or equal to 0.25"))
		}
		if item > 0.75 {
			return go_proto_validators.FieldError("SomeDoubleRep", errors.New("SomeDoubleRep is not smaller than or equal to 0.75"))
		}
	}

	if m.GetSomeFloat() < 0.25 {
		return go_proto_validators.FieldError("SomeFloat", errors.New("SomeFloat is not greater than or equal to 0.25"))
	}
	if m.GetSomeFloat() > 0.75 {
		return go_proto_validators.FieldError("SomeFloat", errors.New("SomeFloat is not smaller than or equal to 0.75"))
	}

	for _, item := range m.GetSomeFloatRep() {
		if item < 0.25 {
			return go_proto_validators.FieldError("SomeFloatRep", errors.New("SomeFloatRep is not greater than or equal to 0.25"))
		}
		if item > 0.75 {
			return go_proto_validators.FieldError("SomeFloatRep", errors.New("SomeFloatRep is not smaller than or equal to 0.75"))
		}
	}

	if string(m.GetSomeNonEmptyString()) == "" {
		return go_proto_validators.FieldError("SomeNonEmptyString", errors.New("SomeNonEmptyString should not be empty"))
	}

	if len(m.GetRepeated()) > 5 {
		return go_proto_validators.FieldError("Repeated", fmt.Errorf("Repeated has %d elements whereas a maximum of 5 is allowed", len(m.GetRepeated())))
	}

	if len(m.GetRepeated()) < 2 {
		return go_proto_validators.FieldError("Repeated", fmt.Errorf("Repeated has %d elements whereas a minimum of 2 is required", len(m.GetRepeated())))
	}

	if len(m.GetSomeStringLtReq()) <= 2 {
		return go_proto_validators.FieldError("SomeStringLtReq", errors.New("SomeStringLtReq should have a length greater than 2"))
	}

	if len(m.GetSomeStringGtReq()) >= 12 {
		return go_proto_validators.FieldError("SomeStringGtReq", errors.New("SomeStringGtReq should have a length smaller than 12"))
	}

	if len(m.GetSomeStringEqReq()) != 10 {
		return go_proto_validators.FieldError("SomeStringEqReq", errors.New("SomeStringEqReq should be of length 10"))
	}

	if len(m.GetSomeBytesLtReq()) <= 5 {
		return go_proto_validators.FieldError("SomeBytesLtReq", errors.New("SomeBytesLtReq should have a length greater than 5"))
	}

	if len(m.GetSomeBytesGtReq()) >= 20 {
		return go_proto_validators.FieldError("SomeBytesGtReq", errors.New("SomeBytesGtReq should have a length smaller than 20"))
	}

	if len(m.GetSomeBytesEqReq()) != 12 {
		return go_proto_validators.FieldError("SomeBytesEqReq", errors.New("SomeBytesEqReq should be of length 12"))
	}

	if !ValidatorMessage3UUIDAnyRE.MatchString(string(m.GetUUIDAny())) {
		return go_proto_validators.FieldError("UUIDAny", errors.New("UUIDAny should match regular expression '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[0][a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}$'"))
	}

	if !ValidatorMessage3UUID4NotEmptyRE.MatchString(string(m.GetUUID4NotEmpty())) {
		return go_proto_validators.FieldError("UUID4NotEmpty", errors.New("UUID4NotEmpty should match regular expression '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[4][a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}$'"))
	}

	if _, ok := EnumProto3_name[int32(m.GetSomeEnum())]; !ok {
		return go_proto_validators.FieldError("SomeEnum", errors.New("someEnum should correspond to a valid enum value"))
	}

	if _, ok := ValidatorMessage3_EmbeddedEnum_name[int32(m.GetSomeEmbeddedEnum())]; !ok {
		return go_proto_validators.FieldError("SomeEmbeddedEnum", errors.New("someEmbeddedEnum should correspond to a valid enum value"))
	}

	return nil
}
