// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.12.3
// source: test/validator_proto3_oneof.proto

package validatortest

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ExternalMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier string `protobuf:"bytes,1,opt,name=Identifier,proto3" json:"Identifier,omitempty"`
	SomeValue  int64  `protobuf:"varint,2,opt,name=SomeValue,proto3" json:"SomeValue,omitempty"`
}

func (x *ExternalMsg) Reset() {
	*x = ExternalMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_validator_proto3_oneof_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalMsg) ProtoMessage() {}

func (x *ExternalMsg) ProtoReflect() protoreflect.Message {
	mi := &file_test_validator_proto3_oneof_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalMsg.ProtoReflect.Descriptor instead.
func (*ExternalMsg) Descriptor() ([]byte, []int) {
	return file_test_validator_proto3_oneof_proto_rawDescGZIP(), []int{0}
}

func (x *ExternalMsg) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *ExternalMsg) GetSomeValue() int64 {
	if x != nil {
		return x.SomeValue
	}
	return 0
}

type OneOfMessage3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SomeInt uint32 `protobuf:"varint,1,opt,name=SomeInt,proto3" json:"SomeInt,omitempty"`
	// Types that are assignable to Type:
	//	*OneOfMessage3_OneMsg
	//	*OneOfMessage3_OneInt
	//	*OneOfMessage3_TwoInt
	Type isOneOfMessage3_Type `protobuf_oneof:"type"`
	// Types that are assignable to Something:
	//	*OneOfMessage3_ThreeInt
	//	*OneOfMessage3_FourInt
	//	*OneOfMessage3_FiveRegex
	Something isOneOfMessage3_Something `protobuf_oneof:"something"`
}

func (x *OneOfMessage3) Reset() {
	*x = OneOfMessage3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_validator_proto3_oneof_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneOfMessage3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfMessage3) ProtoMessage() {}

func (x *OneOfMessage3) ProtoReflect() protoreflect.Message {
	mi := &file_test_validator_proto3_oneof_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfMessage3.ProtoReflect.Descriptor instead.
func (*OneOfMessage3) Descriptor() ([]byte, []int) {
	return file_test_validator_proto3_oneof_proto_rawDescGZIP(), []int{1}
}

func (x *OneOfMessage3) GetSomeInt() uint32 {
	if x != nil {
		return x.SomeInt
	}
	return 0
}

func (m *OneOfMessage3) GetType() isOneOfMessage3_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *OneOfMessage3) GetOneMsg() *ExternalMsg {
	if x, ok := x.GetType().(*OneOfMessage3_OneMsg); ok {
		return x.OneMsg
	}
	return nil
}

func (x *OneOfMessage3) GetOneInt() uint32 {
	if x, ok := x.GetType().(*OneOfMessage3_OneInt); ok {
		return x.OneInt
	}
	return 0
}

func (x *OneOfMessage3) GetTwoInt() uint32 {
	if x, ok := x.GetType().(*OneOfMessage3_TwoInt); ok {
		return x.TwoInt
	}
	return 0
}

func (m *OneOfMessage3) GetSomething() isOneOfMessage3_Something {
	if m != nil {
		return m.Something
	}
	return nil
}

func (x *OneOfMessage3) GetThreeInt() uint32 {
	if x, ok := x.GetSomething().(*OneOfMessage3_ThreeInt); ok {
		return x.ThreeInt
	}
	return 0
}

func (x *OneOfMessage3) GetFourInt() uint32 {
	if x, ok := x.GetSomething().(*OneOfMessage3_FourInt); ok {
		return x.FourInt
	}
	return 0
}

func (x *OneOfMessage3) GetFiveRegex() string {
	if x, ok := x.GetSomething().(*OneOfMessage3_FiveRegex); ok {
		return x.FiveRegex
	}
	return ""
}

type isOneOfMessage3_Type interface {
	isOneOfMessage3_Type()
}

type OneOfMessage3_OneMsg struct {
	OneMsg *ExternalMsg `protobuf:"bytes,2,opt,name=one_msg,json=oneMsg,proto3,oneof"`
}

type OneOfMessage3_OneInt struct {
	OneInt uint32 `protobuf:"varint,3,opt,name=one_int,json=oneInt,proto3,oneof"`
}

type OneOfMessage3_TwoInt struct {
	TwoInt uint32 `protobuf:"varint,4,opt,name=two_int,json=twoInt,proto3,oneof"`
}

func (*OneOfMessage3_OneMsg) isOneOfMessage3_Type() {}

func (*OneOfMessage3_OneInt) isOneOfMessage3_Type() {}

func (*OneOfMessage3_TwoInt) isOneOfMessage3_Type() {}

type isOneOfMessage3_Something interface {
	isOneOfMessage3_Something()
}

type OneOfMessage3_ThreeInt struct {
	ThreeInt uint32 `protobuf:"varint,5,opt,name=three_int,json=threeInt,proto3,oneof"`
}

type OneOfMessage3_FourInt struct {
	FourInt uint32 `protobuf:"varint,6,opt,name=four_int,json=fourInt,proto3,oneof"`
}

type OneOfMessage3_FiveRegex struct {
	FiveRegex string `protobuf:"bytes,7,opt,name=five_regex,json=fiveRegex,proto3,oneof"`
}

func (*OneOfMessage3_ThreeInt) isOneOfMessage3_Something() {}

func (*OneOfMessage3_FourInt) isOneOfMessage3_Something() {}

func (*OneOfMessage3_FiveRegex) isOneOfMessage3_Something() {}

var File_test_validator_proto3_oneof_proto protoreflect.FileDescriptor

var file_test_validator_proto3_oneof_proto_rawDesc = []byte{
	0x0a, 0x21, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x74, 0x65,
	0x73, 0x74, 0x1a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x77, 0x69, 0x74, 0x6b, 0x6f, 0x77, 0x2f, 0x67, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a, 0x0b, 0x45,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x73, 0x67, 0x12, 0x32, 0x0a, 0x0a, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x12,
	0xe2, 0xdf, 0x1f, 0x0e, 0x0a, 0x0c, 0x5e, 0x5b, 0x61, 0x2d, 0x7a, 0x5d, 0x7b, 0x32, 0x2c, 0x35,
	0x7d, 0x24, 0x52, 0x0a, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x26,
	0x0a, 0x09, 0x53, 0x6f, 0x6d, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x42, 0x08, 0xe2, 0xdf, 0x1f, 0x04, 0x10, 0x00, 0x18, 0x64, 0x52, 0x09, 0x53, 0x6f, 0x6d,
	0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xcc, 0x02, 0x0a, 0x0d, 0x4f, 0x6e, 0x65, 0x4f, 0x66,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x33, 0x12, 0x20, 0x0a, 0x07, 0x53, 0x6f, 0x6d, 0x65,
	0x49, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x10,
	0x0a, 0x52, 0x07, 0x53, 0x6f, 0x6d, 0x65, 0x49, 0x6e, 0x74, 0x12, 0x35, 0x0a, 0x07, 0x6f, 0x6e,
	0x65, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x6e, 0x65, 0x4d, 0x73,
	0x67, 0x12, 0x21, 0x0a, 0x07, 0x6f, 0x6e, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x10, 0x14, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x6e,
	0x65, 0x49, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x07, 0x74, 0x77, 0x6f, 0x5f, 0x69, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x10, 0x64, 0x48, 0x00, 0x52,
	0x06, 0x74, 0x77, 0x6f, 0x49, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x09, 0x74, 0x68, 0x72, 0x65, 0x65,
	0x5f, 0x69, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02,
	0x10, 0x14, 0x48, 0x01, 0x52, 0x08, 0x74, 0x68, 0x72, 0x65, 0x65, 0x49, 0x6e, 0x74, 0x12, 0x23,
	0x0a, 0x08, 0x66, 0x6f, 0x75, 0x72, 0x5f, 0x69, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d,
	0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x10, 0x64, 0x48, 0x01, 0x52, 0x07, 0x66, 0x6f, 0x75, 0x72,
	0x49, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x0a, 0x66, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x65, 0x67, 0x65,
	0x78, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x42, 0x12, 0xe2, 0xdf, 0x1f, 0x0e, 0x0a, 0x0c, 0x5e,
	0x5b, 0x61, 0x2d, 0x7a, 0x5d, 0x7b, 0x32, 0x2c, 0x35, 0x7d, 0x24, 0x48, 0x01, 0x52, 0x09, 0x66,
	0x69, 0x76, 0x65, 0x52, 0x65, 0x67, 0x65, 0x78, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x42, 0x13, 0x0a, 0x09, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x06, 0xea,
	0xdf, 0x1f, 0x02, 0x08, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_validator_proto3_oneof_proto_rawDescOnce sync.Once
	file_test_validator_proto3_oneof_proto_rawDescData = file_test_validator_proto3_oneof_proto_rawDesc
)

func file_test_validator_proto3_oneof_proto_rawDescGZIP() []byte {
	file_test_validator_proto3_oneof_proto_rawDescOnce.Do(func() {
		file_test_validator_proto3_oneof_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_validator_proto3_oneof_proto_rawDescData)
	})
	return file_test_validator_proto3_oneof_proto_rawDescData
}

var file_test_validator_proto3_oneof_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_validator_proto3_oneof_proto_goTypes = []interface{}{
	(*ExternalMsg)(nil),   // 0: validatortest.ExternalMsg
	(*OneOfMessage3)(nil), // 1: validatortest.OneOfMessage3
}
var file_test_validator_proto3_oneof_proto_depIdxs = []int32{
	0, // 0: validatortest.OneOfMessage3.one_msg:type_name -> validatortest.ExternalMsg
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_test_validator_proto3_oneof_proto_init() }
func file_test_validator_proto3_oneof_proto_init() {
	if File_test_validator_proto3_oneof_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_validator_proto3_oneof_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_validator_proto3_oneof_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneOfMessage3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_test_validator_proto3_oneof_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*OneOfMessage3_OneMsg)(nil),
		(*OneOfMessage3_OneInt)(nil),
		(*OneOfMessage3_TwoInt)(nil),
		(*OneOfMessage3_ThreeInt)(nil),
		(*OneOfMessage3_FourInt)(nil),
		(*OneOfMessage3_FiveRegex)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_validator_proto3_oneof_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_validator_proto3_oneof_proto_goTypes,
		DependencyIndexes: file_test_validator_proto3_oneof_proto_depIdxs,
		MessageInfos:      file_test_validator_proto3_oneof_proto_msgTypes,
	}.Build()
	File_test_validator_proto3_oneof_proto = out.File
	file_test_validator_proto3_oneof_proto_rawDesc = nil
	file_test_validator_proto3_oneof_proto_goTypes = nil
	file_test_validator_proto3_oneof_proto_depIdxs = nil
}
