package plugin

const (
	BAD_REQ_REGEX     = "BAD_REQ_REGEX"
	BAD_REQ_GT        = "BAD_REQ_GT"
	BAD_REQ_LT        = "BAD_REQ_LT"
	BAD_REQ_EXIST     = "BAD_REQ_EXIST"
	BAD_REQ_GTE       = "BAD_REQ_GTE"
	BAD_REQ_LTE       = "BAD_REQ_LTE"
	BAD_REQ_NOTEMPTY  = "BAD_REQ_NOTEMPTY"
	BAD_REQ_COUNTMIN  = "BAD_REQ_COUNTMIN"
	BAD_REQ_COUNTMAX  = "BAD_REQ_COUNTMAX"
	BAD_REQ_LENGTHGT  = "BAD_REQ_LENGTHGT"
	BAD_REQ_LENGTHGTE = "BAD_REQ_LENGTHGTE"
	BAD_REQ_LENGTHLT  = "BAD_REQ_LENGTHLT"
	BAD_REQ_LENGTHEQ  = "BAD_REQ_LENGTHEQ"
	BAD_REQ_INENUM    = "BAD_REQ_INENUM"
	BAD_REQ_UUID      = "BAD_REQ_UUID"
)
