// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: examples/enum.proto

/*
Package validator_examples is a generated protocol buffer package.

It is generated from these files:
	examples/enum.proto
	examples/nested.proto

It has these top-level messages:
	SomeMsg
	InnerMessage
	OuterMessage
*/
package validator_examples

import fmt "fmt"
import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *SomeMsg) Validate() error {
	if name, ok := Action_name[this.Do]; !ok {
		return go_proto_validators.FieldError("Do", fmt.Errorf(`value '%v' must be a valid Action field`, this.Do))
	}
	return nil
}
