// Code generated by protoc-gen-govalidators. DO NOT EDIT.

package validator_examples

import (
	errors "errors"
	go_proto_validators "github.com/mwitkow/go-proto-validators"
	regexp "regexp"
)

var UUIDMsgUserIdRE = regexp.MustCompile(`^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[4][a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}$`)

func (m *UUIDMsg) Validate() error {
	if !UUIDMsgUserIdRE.MatchString(string(m.GetUserId())) {
		return go_proto_validators.FieldError("UserId", errors.New("user_id should match regular expression '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[4][a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}$'"))
	}

	return nil
}
